name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC.

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Initialize Day Counter
      run: |
        # Create day-count.txt if it doesn't exist
        if [ ! -f day-count.txt ]; then
          echo "1" > day-count.txt
        fi

    - name: Increment and Log Day
      run: |
        # Read and increment the day count
        DAY_COUNT=$(cat day-count.txt)
        echo "Day $DAY_COUNT" >> commit-log.txt
        NEW_DAY_COUNT=$((DAY_COUNT + 1))
        echo "$NEW_DAY_COUNT" > day-count.txt

    - name: Commit Changes
      run: |
        # Set GitHub username and email to attribute the commit to you
        git config --global user.email "your-email@example.com"  # Use your GitHub email
        git config --global user.name "your-github-username"  # Use your GitHub username
        git add .
        git commit -m "Automated daily commit: Day $DAY_COUNT" --allow-empty

    - name: Push Changes
      env:
        TOKEN: ${{ secrets.PAT }}
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/saralbjr/commit.git
        git push
