name: Daily Commit

on:
  schedule:
    - cron: "0 0 * * *" # This will run the action every day at midnight UTC.

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Make Changes
        run: |
          # Make changes to a specific file, or add a timestamp
          echo "$(date)" >> commit-log.txt  # This will add a timestamp to `commit-log.txt` daily.

      - name: Commit Changes
        run: |
          git config --global user.email "rmanbajra@gmail.com"
          git config --global user.name "saralbjr"
          git add .
          git commit -m "Automated daily commit"

      - name: Push Changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push
